name: CI
on:
  push:
    branches: [main]

jobs:
  build:
     runs-on: ubuntu-lastest

     steps:
       - uses: actions/checkout@v2


       - name: Get Date
         id : get-date
         run: |
           echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
         shell: bash
        
       -  name: Cache Buildozer global directory
          uses: actions/cache@v2
          with:
             path: builderdozer_global
             key: buildozer-global-${{ hashFiles('buildozer.spec') }} 

       - uses: actions/cache@v2
         with:
           path: .buildozer
           key: ${{ runner.os }}-${{ steps.get.date }}-${{ hashFiles('buildozer.spec')}}

       - name: Build with Buildozer
         uses: ArstemSBulgakov/buildozer-action@v1
         id: buildozer
         with:
            command: buildozer android debug
            buildozer_versions: master

       - name: Upload artifacts
         uses:  actions/upload_artfacts@v2
         with:
           name: package
           path: ${{ steps.buildozer.outputs.filename }}
